services:
  postgres:
    # IMAGEM ALTERADA PARA A VERSÃO 16, MAIS RECENTE E COMPATÍVEL
    image: postgres:16
    container_name: conectta-db
    environment:
      POSTGRES_USER: conectta_user
      POSTGRES_PASSWORD: conectta_password
      POSTGRES_DB: conectta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conectta_user -d conectta_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: